### PR TITLE
Add logging

### PR DESCRIPTION
**Pull request by pjanik**
[#176563068]

### CODE REVIEW

**Comment by knowuh** [comment]
@pjanik -- I am going to have a look at this this morning, but FYI some tests are failing.

**Comment by knowuh** [comment]
@pjanik -- it looks like the build failed because the AWS command line tools couldn't be installed using pip.  Might be an intermittent failure, worth just retrying the build in pace.

**Review by knowuh — APPROVED** [review]
Looks good, thanks.

**Comment by pjanik** [comment]
Thanks. I think I had the same problem in Wildfires, so I'll fix it before merging. As usual, things stop working in TravisCI over time 🥀 This project hasn't been deployed for a while.

**Comment by kswenson** [comment]
From slack:

>Doug Martin 6:47 AM
UPDATE: for FINAL posterity the REAL fix is to set the Python version using this line before installing the aws cli:
`- travis_retry pyenv global 3.6`

**Comment by pjanik** [comment]
Thanks. Actually, I think that AWS CLI is only necessary for manual invalidation. And I don't think we even need it. Here's a PR in the starter repo: https://github.com/concord-consortium/starter-projects/pull/17
But PRs there have a bit of inertia, so it never got merged. :wink:

**Comment by kswenson** [comment]
The starter project is now using GitHub actions so it's no longer an example of Travis usage. Without the manual invalidation there is still a delay between deployment of the build and its availability to browsers which is nominally ten minutes but we've seen it take longer.

**Comment by pjanik** [comment]
I think there were some issues with manual invalidation and that's why @scytacki wanted to remove it, but at this point, I don't remember what was that.

**Comment by scytacki** [comment]
My issues are nuanced. The caching of the requests are done both by CloudFront and browsers. So just because you manually invalidate CloudFront, you can't invalidate the browser. So relying on the CloudFront invalidate gives a false impression that the changes will be seen immediately by everyone. That is only true if everyone does `shift-reload` in their browser. I'm not sure, but I think in some cases the reload behavior in iframes does not always respect the `shift-reload`.

The ideal setup is more like this one: https://github.com/concord-consortium/starter-projects/pull/37
In that setup there is just one small file (index.html) that needs to be downloaded and then it refers to versioned files for everything else. So that file can have a really short cache time. And then there is no need for CF invalidations.

But we aren't using that approach yet, so in the meantime, if you think the invalidations are more helpful than hurtful feel free to use them.

**Comment by kswenson** [comment]
>My issues are nuanced. The caching of the requests are done both by CloudFront and browsers. So just because you manually invalidate CloudFront, you can't invalidate the browser. So relying on the CloudFront invalidate gives a false impression that the changes will be seen immediately by everyone.

My reason for preferring the invalidation is more about developer friction than user impact. It's easy for us to empty browser cache or run without browser cache, but having to wait for CloudFront invalidation can be annoying and/or confusing. Toward that end, it's mostly an issue for branch builds which have no user impact but significant developer impact, although even with production builds I like to test that the deploy worked immediately after the deploy rather than waiting for natural invalidation.

**Pull request merged**
